from selenium import webdriver
import time

driver = webdriver.Chrome("/usr/lib/chromium-browser/chromedriver")
driver.implicitly_wait(10)
driver.maximize_window()

# TASK 1
driver.get("https://www.charmhealth.com/")
driver.implicitly_wait(10)
Login_click = driver.find_element_by_class_name("sign-button").click()
print("clicked on the log in button")
time.sleep(2)
usrname = driver.find_element_by_name("lid").send_keys("dev+7@deepscribe.ai")
print("sended the username")
time.sleep(2)
password = driver.find_element_by_name("pwd").send_keys("vgS9Y3RDhq2tnhE")
print("sended the password")
time.sleep(2)
Redsignin_click = driver.find_element_by_id("signin_submit").click()
print("signin button clicked ")
time.sleep(5)
X_button = driver.find_element_by_css_selector('''#NEW_DIALOG_CLOSE_MARK''').click()
print("X button clicked ")
time.sleep(3)
chart_menu = driver.find_element_by_css_selector("#MEMBER_TAB_ID_2 > div > i").click()
print("Chart_menu clicked ")
time.sleep(5)
# encounter = driver.find_element_by_xpath("//*[@id='newEncButDiv']/div").click()
# print("encounter button clicked ")

# TASK 2
sample_data = {
"name": "Dummy Patient",
"History of Present Illness": "Patient presents today for concerns regarding his palpitations, but nothing he thinks is serious. He notes that he can use his Apple Watch when he experiences these palpitations. He denies having passed out. Patient’s event monitor shows that he had an auto trigger 14 times, but nothing critical. His lowest heart rate was 39 and high highest heart rate was 157. There is only sinus rhythm. When patient passed out on the tilt table, his blood pressure dropped from 109/74 to 80/63 and after his blood pressure dropped, his heart rate that was 90 dropped as well. Patient quit smoking. Current medications include: Cyproheptadine, Lexapro 10mg",
"Physical Examination": {"Template": "IM Skin Growth - PE", "Checkboxes": [["scaling"], ["lesion", "color", "blue"]], "Values": {"Hypomelanotic Size": "70mm"}},
"Diagnoses": [{"Diagnosis": "Essential (primary) hypertension", "Code": "I10"}]
}
title = driver.find_element_by_xpath("//*[@id='encounterTitle_569635000000061005']").click()
print("Title clicked ")
time.sleep(3)
edit = driver.find_element_by_xpath("//*[@id='pastEncButton']").click()
print("edit clicked ")
time.sleep(3)
history = driver.find_element_by_xpath("//*[@id='encounterTab_2']").click()
print("history clicked ")
time.sleep(5)
text= driver.find_element_by_xpath("//div[@id='editor_2']//iframe[@class='ze_area']").send_keys("Patient presents today for concerns regarding his palpitations, but nothing he thinks is serious. He notes that he can use his Apple Watch when he experiences these palpitations. He denies having passed out. Patient’s event monitor shows that he had an auto trigger 14 times, but nothing critical. His lowest heart rate was 39 and high highest heart rate was 157. There is only sinus rhythm. When patient passed out on the tilt table, his blood pressure dropped from 109/74 to 80/63 and after his blood pressure dropped, his heart rate that was 90 dropped as well. Patient quit smoking. Current medications include: Cyproheptadine, Lexapro 10mg")
print("Text Entered")
time.sleep(30)
physical_exam = driver.find_element_by_xpath("//div[@id='encounterTab_3']").click()
print("physical_exam")
time.sleep(2)
templet = driver.find_element_by_xpath("//*[@id='PE_VIEW']/div/table/tbody/tr/td/div[3]/div[1]").click()
print("templet")
time.sleep(2)
dropdown = driver.find_element_by_xpath("//*[@id='lftContainer']/ul/ul/li[47]").click()
time.sleep(2)
print("dropdown")
scalling_checkbox = driver.find_element_by_xpath("//*[@id='VALUE_46_0_3_569635000000029581']").click()
time.sleep(2)
print("scalling check box")
lession_checkbox = driver.find_element_by_xpath("//*[@id='VALUE_46_0_10_569635000000029581']").click()
time.sleep(2)
print("lession checkbox")
colour = driver.find_element_by_xpath("//*[@id='VALUE_46_0_17_569635000000029581']").click()
time.sleep(2)
print("color checkbox")
red = driver.find_element_by_xpath("//*[@id='VALUE_46_0_23_569635000000029581']").click()
time.sleep(2)
print("red checkbox")
pomelantic = driver.find_element_by_xpath("//*[@id='VALUE_569635000000029581']").send_keys("70 mm")
time.sleep(2)
print("pomelantic text entered")
okbutton = driver.find_element_by_xpath("//*[@id='tDialogContent']/div/div[4]/button[1]").click()
time.sleep(2)
print("okbutton clicked")
diagonasis = driver.find_element_by_xpath("//*[@id='encounterTab_6']").click()
time.sleep(2)
print("diagonasis clicked")
adddx = driver.find_element_by_xpath("//*[@id='encounterPart_6']/div/table/tbody/tr/td/div[1]/div[2]/div[3]").click()
time.sleep(2)
print("adddx clicked")
Diagnosis = driver.find_element_by_xpath("//*[@id='diagnosis_0']").send_keys("Hyperaemia")
time.sleep(2)
print("Diagnosis clicked")
dropdownselection = driver.find_element_by_xpath("//*[@id='diagnosisSearchList']/ul/li[1]").click()
time.sleep(2)
print("dropdownselection clicked")
savebutton = driver.find_element_by_xpath("//*[@id='saveContentDiv']").click()
time.sleep(2)
print("save button clicked")
driver.close()
driver.quit()